### ISSUE TITLE
Suggestion: mongoose as a peer dependency

### ISSUE THREAD

**Issue by SeanLMcCullough** [uncledent/mongoose-cursor-pagination-plugin#7]
Since the version of Mongoose used in this plugin is outdated, it's not possible to use in newer projects due to conflicts:

```
TypeError: Schema for array path `contactDetails` is from a different copy of the Mongoose module. Please make sure you're using the same version of Mongoose everywhere with `npm list mongoose`.
```

Would it be feasible to include mongoose as a peer dependency instead, allowing use of more modern versions of Mongoose as the plugin ages?

Thanks for putting this plugin together, this really has an upper hand over the original library with its native use of the Mongoose models.

**Comment by uncledent** [comment]
Done thanks to @grantmcdade
